/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: 'var(--color-primary)',
          'primary-vivid': 'var(--color-primary-vivid)',
          'primary-light': 'var(--color-primary-light)',
          'primary-dark': 'var(--color-primary-dark)',
          'primary-deep': 'var(--color-primary-deep)',
          secondary: 'var(--color-secondary)',
          'secondary-light': 'var(--color-secondary-light)',
          'secondary-dark': 'var(--color-secondary-dark)',
          accent: 'var(--color-accent)',
        },
        'subnav-bg': 'var(--color-subnav-bg)',
        'tab-accent': 'var(--color-tab-accent)',
        'tab-bg': 'var(--color-tab-bg)',
        'select-bg': 'var(--color-select-bg)',
        'select-placeholder': 'var(--color-select-placeholder)',
        'dropdown-border': 'var(--color-dropdown-border)',
        'dropdown-value-bg': 'var(--color-dropdown-value-bg)',
        card: {
          'header-text': 'var(--color-card-header-text)',
          'body-bg': 'var(--color-card-body-bg)',
          'body-text': 'var(--color-card-body-text)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          900: 'var(--color-neutral-900)',
        },
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        'success-dark': 'var(--color-success-dark)',
        'warning-dark': 'var(--color-warning-dark)',
        'error-dark': 'var(--color-error-dark)',
        'map-bg': 'var(--color-map-bg)',
        table: {
          'header-bg': 'var(--color-table-header-bg)',
          'sticky-row-even': 'var(--color-table-sticky-row-even)',
          'sticky-row-odd': 'var(--color-table-sticky-row-odd)',
          'sticky-text': 'var(--color-table-sticky-text)',
          'row-even': 'var(--color-table-row-even)',
          'row-odd': 'var(--color-table-row-odd)',
          'body-text': 'var(--color-table-body-text)',
        },
        'btn-secondary': {
          bg: 'var(--btn-secondary-bg)',
          text: 'var(--btn-secondary-text)',
          border: 'var(--btn-secondary-border)',
          'bg-hover': 'var(--btn-secondary-bg-hover)',
          'text-hover': 'var(--btn-secondary-text-hover)',
        },
        cancel: 'var(--btn-cancel)',
        modal: {
          'header-bg': 'var(--color-modal-header-bg)',
          'studies-bg': 'var(--color-modal-studies-bg)',
        },
        quadrant: {
          'top-priority-bg': 'var(--color-quadrant-top-priority-bg)',
          'long-term-bg': 'var(--color-quadrant-long-term-bg)',
          'urgent-bg': 'var(--color-quadrant-urgent-bg)',
          'lower-bg': 'var(--color-quadrant-lower-bg)',
        },
        icon: {
          etiology: 'var(--color-icon-etiology)',
          diagnosis: 'var(--color-icon-diagnosis)',
          cyan: 'var(--color-icon-cyan)',
          teal: 'var(--color-icon-teal)',
          orange: 'var(--color-icon-orange)',
        },
        // --- MOA Overview Section Icon Backgrounds ---
        moa: {
          'molecular-bg': 'var(--color-moa-molecular-bg)',
          'pattern-bg': 'var(--color-moa-pattern-bg)',
          'landscape-bg': 'var(--color-moa-landscape-bg)',
        },

        // --- Disease Pathophysiology Section Card Backgrounds ---
        section: {
          'etiology-bg': 'var(--color-section-etiology-bg)',
          'symptoms-bg': 'var(--color-section-symptoms-bg)',
          'prevalence-bg': 'var(--color-section-prevalence-bg)',
          'diagnosis-bg': 'var(--color-section-diagnosis-bg)',
          'patients-bg': 'var(--color-section-patients-bg)',
          'specialists-bg': 'var(--color-section-specialists-bg)',
          'treatments-bg': 'var(--color-section-treatments-bg)',
        },
        si: {
          'header-1': 'var(--color-si-header-1-bg)',
          'header-2': 'var(--color-si-header-2-bg)',
          'header-3': 'var(--color-si-header-3-bg)',
          '1-label': 'var(--color-si-1-label)',
          '1-title': 'var(--color-si-1-title)',
          '2-label': 'var(--color-si-2-label)',
          '2-title': 'var(--color-si-2-title)',
          '3-label': 'var(--color-si-3-label)',
          '3-title': 'var(--color-si-3-title)',
        },
        mo: {
          'badge-text': 'var(--color-mo-badge-text)',
          'badge-bg': 'var(--color-mo-badge-bg)',
        },
        chart: {
          grid: 'var(--color-chart-grid)',
          'tick-muted': 'var(--color-chart-tick-muted)',
          'tick-mid': 'var(--color-chart-tick-mid)',
          label: 'var(--color-chart-label)',

          'teal-dark': 'var(--color-chart-teal-dark)',
          teal: 'var(--color-chart-teal)',
          'teal-light': 'var(--color-chart-teal-light)',
          mauve: 'var(--color-chart-mauve)',
          'pink-light': 'var(--color-chart-pink-light)',

          region: {
            na: 'var(--color-chart-region-na)',
            eu: 'var(--color-chart-region-eu)',
            apac: 'var(--color-chart-region-apac)',
            latam: 'var(--color-chart-region-latam)',
            mea: 'var(--color-chart-region-mea)',
          },

          severity: {
            mild: 'var(--color-chart-severity-mild)',
            moderate: 'var(--color-chart-severity-moderate)',
            severe: 'var(--color-chart-severity-severe)',
            refractory: 'var(--color-chart-severity-refractory)',
          },

          ms: {
            1: 'var(--color-chart-ms-1)',
            2: 'var(--color-chart-ms-2)',
            3: 'var(--color-chart-ms-3)',
            4: 'var(--color-chart-ms-4)',
            5: 'var(--color-chart-ms-5)',
            6: 'var(--color-chart-ms-6)',
            7: 'var(--color-chart-ms-7)',
            8: 'var(--color-chart-ms-8)',
            9: 'var(--color-chart-ms-9)',
          },
        },
        vision: 'var(--color-vision)',
        badge: {
          'experts-text': 'var(--color-badge-experts-text)',
          'experts-bg': 'var(--color-badge-experts-bg)',
          'experts-dot': 'var(--color-badge-experts-dot)',
          'planning-text': 'var(--color-badge-planning-text)',
          'planning-bg': 'var(--color-badge-planning-bg)',
          'planning-dot': 'var(--color-badge-planning-dot)',
          'market-text': 'var(--color-badge-market-text)',
          'market-bg': 'var(--color-badge-market-bg)',
          'market-dot': 'var(--color-badge-market-dot)',
          'congress-text': 'var(--color-badge-congress-text)',
          'congress-bg': 'var(--color-badge-congress-bg)',
          'congress-dot': 'var(--color-badge-congress-dot)',
        },
        link: 'var(--color-link)',
        'text-heading': 'var(--color-text-heading)',
        'text-dark': 'var(--color-text-dark)',
        'text-mid': 'var(--color-text-mid)',
        'text-muted': 'var(--color-text-muted)',
        'text-subtle': 'var(--color-text-subtle)',
        'text-body': 'var(--color-text-body)',
        exec: {
          'icon-bg': 'var(--color-exec-icon-bg)',
          'row-bg': 'var(--color-exec-row-bg)',
          'new-badge-bg': 'var(--color-exec-new-badge-bg)',
        },
        'sidebar-border': 'var(--color-sidebar-border)',
        'chat-placeholder': 'var(--color-chat-placeholder)',
        'prompt-card-border': 'var(--color-prompt-card-border)',
        'prompt-card-text': 'var(--color-prompt-card-text)',
        'agent-subtitle':          'var(--color-agent-subtitle)',
        'agent-select-label':      'var(--color-agent-select-label)',
        'agent-card-border':       'var(--color-agent-card-border)',
        'agent-category':          'var(--color-agent-category-text)',
        'agent-card-expanded-bg':  'var(--color-agent-card-expanded-bg)',
        'agent-checkbox-border':   'var(--color-agent-checkbox-border)',
        'agent-checked-title':     'var(--color-agent-checked-title)',
        'success-banner-bg':       'var(--color-success-banner-bg)',
        'success-text':            'var(--color-success-text)',
        'run-again':               'var(--color-run-again)',
        'bg-row-alt': 'var(--color-bg-row-alt)',
        'bg-filter-bar': 'var(--color-bg-filter-bar)',
        'bg-stat-card-wrap': 'var(--color-bg-stat-card-wrap)',
        'primary-tint': {
          '04': 'var(--color-primary-tint-04)',
          10: 'var(--color-primary-tint-10)',
          25: 'var(--color-primary-tint-25)',
          45: 'var(--color-primary-tint-45)',
        },

        // --- Error / Form State Colors ---
        'error-bg': 'var(--color-error-bg)',
        'error-border': 'var(--color-error-border)',
        'error-text': 'var(--color-error-text)',
        'error-icon': 'var(--color-error-icon)',

        // --- Links ---
        'link-bright': 'var(--color-link-bright)',

        // --- SubNav / Tab Extras ---
        'tab-inactive': 'var(--color-tab-inactive)',
        'tab-inactive-90': 'var(--color-tab-inactive-90)',
        'subnav-meta': 'var(--color-subnav-meta)',
        'subnav-asset': 'var(--color-subnav-asset)',
        'near-black': 'var(--color-text-near-black)',
        'topbar-divider': 'var(--color-topbar-divider)',
        'topbar-text': 'var(--color-topbar-text)',
        'topbar-ai-badge': 'var(--color-topbar-ai-badge-bg)',

        // --- Section UI ---
        'section-divider': 'var(--color-section-divider)',
        'section-title': 'var(--color-section-title-bg)',

        // --- Research Documents Sidebar ---
        rd: {
          'section-label': 'var(--color-rd-section-label)',
          count: 'var(--color-rd-count)',
          'count-badge': 'var(--color-rd-count-badge-bg)',
          divider: 'var(--color-rd-divider)',
          'body-bg': 'var(--color-rd-body-bg)',
          'card-border': 'var(--color-rd-card-border)',
          'avatar-bg': 'var(--color-rd-avatar-bg)',
          'avatar-text': 'var(--color-rd-avatar-text)',
          'owner-name': 'var(--color-rd-owner-name)',
          description: 'var(--color-rd-description)',
          'tag-my-doc-text': 'var(--color-rd-tag-my-doc-text)',
          'tag-can-edit-text': 'var(--color-rd-tag-can-edit-text)',
          'tag-view-only-bg': 'var(--color-rd-tag-view-only-bg)',
          'tag-view-only-text': 'var(--color-rd-tag-view-only-text)',
          trash: 'var(--color-rd-trash)',
          'search-bg': 'var(--color-rd-search-bg)',
          'search-border': 'var(--color-rd-search-border)',
          'search-placeholder': 'var(--color-rd-search-placeholder)',
          'sort-border': 'var(--color-rd-sort-border)',
          'note-tag-bg': 'var(--color-rd-note-tag-bg)',
          'note-tag-text': 'var(--color-rd-note-tag-text)',
          'note-selected-bg': 'var(--color-rd-note-selected-bg)',
          'note-title':           'var(--color-rd-note-title)',
          'note-body':            'var(--color-rd-note-body)',
          'new-note-bg':          'var(--color-rd-new-note-bg)',
          'new-note-placeholder': 'var(--color-rd-new-note-placeholder)',
          'comment-bg':     'var(--color-rd-comment-bg)',
          'comment-text':   'var(--color-rd-comment-text)',
          'edit-banner-bg': 'var(--color-rd-edit-banner-bg)',
          'edit-hint':      'var(--color-rd-edit-hint)',
          'cancel-border':  'var(--color-rd-cancel-border)',
          'cancel-text':    'var(--color-rd-cancel-text)',
          'edit-count':     'var(--color-rd-edit-count)',
          'chat-user-bg':   'var(--color-rd-chat-user-bg)',
          'chat-border':    'var(--color-rd-chat-border)',
        },

        // --- Avatar Palette (solid) ---
        av: {
          1: 'var(--color-av-1)',
          2: 'var(--color-av-2)',
          3: 'var(--color-av-3)',
          4: 'var(--color-av-4)',
          5: 'var(--color-av-5)',
          6: 'var(--color-av-6)',
          7: 'var(--color-av-7)',
          8: 'var(--color-av-8)',
        },

        // --- Avatar Chip Palette (light bg + dark text) ---
        'av-chip': {
          '1-bg':   'var(--color-av-chip-1-bg)',
          '1-text': 'var(--color-av-chip-1-text)',
          '2-bg':   'var(--color-av-chip-2-bg)',
          '2-text': 'var(--color-av-chip-2-text)',
          '3-bg':   'var(--color-av-chip-3-bg)',
          '3-text': 'var(--color-av-chip-3-text)',
          '4-bg':   'var(--color-av-chip-4-bg)',
          '4-text': 'var(--color-av-chip-4-text)',
          '5-bg':   'var(--color-av-chip-5-bg)',
          '5-text': 'var(--color-av-chip-5-text)',
          '6-bg':   'var(--color-av-chip-6-bg)',
          '6-text': 'var(--color-av-chip-6-text)',
          '7-bg':   'var(--color-av-chip-7-bg)',
          '7-text': 'var(--color-av-chip-7-text)',
          '8-bg':   'var(--color-av-chip-8-bg)',
          '8-text': 'var(--color-av-chip-8-text)',
        },

        // --- SWOT Category Colors ---
        swot: {
          'strengths-border': 'var(--color-swot-strengths-border)',
          'strengths-bg': 'var(--color-swot-strengths-bg)',
          'strengths-text': 'var(--color-swot-strengths-text)',
          'weaknesses-border': 'var(--color-swot-weaknesses-border)',
          'weaknesses-bg': 'var(--color-swot-weaknesses-bg)',
          'weaknesses-text': 'var(--color-swot-weaknesses-text)',
          'opportunities-border': 'var(--color-swot-opportunities-border)',
          'opportunities-bg': 'var(--color-swot-opportunities-bg)',
          'opportunities-text': 'var(--color-swot-opportunities-text)',
          'threats-border': 'var(--color-swot-threats-border)',
          'threats-bg': 'var(--color-swot-threats-bg)',
          'threats-text': 'var(--color-swot-threats-text)',
        },

        // --- Strategic Imperative Card Schemes ---
        'si-card': {
          'orange-bg': 'var(--color-si-card-orange-bg)',
          'orange-border': 'var(--color-si-card-orange-border)',
          'orange-badge': 'var(--color-si-card-orange-badge)',
          'blue-bg': 'var(--color-si-card-blue-bg)',
          'blue-border': 'var(--color-si-card-blue-border)',
          'blue-badge': 'var(--color-si-card-blue-badge)',
          'teal-bg': 'var(--color-si-card-teal-bg)',
          'teal-border': 'var(--color-si-card-teal-border)',
          'teal-badge': 'var(--color-si-card-teal-badge)',
        },

        // --- Gap Priority & Urgency Badges ---
        'gap-priority': {
          'high-bg': 'var(--color-gap-priority-high-bg)',
          'medium-bg': 'var(--color-gap-priority-medium-bg)',
          'low-bg': 'var(--color-gap-priority-low-bg)',
          'low-text': 'var(--color-gap-priority-low-text)',
        },
        'gap-urgency': {
          bg: 'var(--color-gap-urgency-bg)',
          text: 'var(--color-gap-urgency-text)',
        },

        // --- KDM Priority Badges ---
        'kdm-priority': {
          'high-bg': 'var(--color-kdm-priority-high-bg)',
          'high-text': 'var(--color-kdm-priority-high-text)',
          'medium-bg': 'var(--color-kdm-priority-medium-bg)',
          'medium-text': 'var(--color-kdm-priority-medium-text)',
          'low-bg': 'var(--color-kdm-priority-low-bg)',
          'low-text': 'var(--color-kdm-priority-low-text)',
          'sp-bg': 'var(--color-kdm-priority-sp-bg)',
          'sp-text': 'var(--color-kdm-priority-sp-text)',
        },

        // --- Shared Tag Colors ---
        tag: {
          'teal-bg': 'var(--color-tag-teal-bg)',
          'teal-text': 'var(--color-tag-teal-text)',
          'violet-bg': 'var(--color-tag-violet-bg)',
          'violet-text': 'var(--color-tag-violet-text)',
          'indigo-bg': 'var(--color-tag-indigo-bg)',
          'indigo-text': 'var(--color-tag-indigo-text)',
          'pink-bg': 'var(--color-tag-pink-bg)',
          'pink-text': 'var(--color-tag-pink-text)',
          'cyan-bg': 'var(--color-tag-cyan-bg)',
          'cyan-text': 'var(--color-tag-cyan-text)',
          'rose-bg': 'var(--color-tag-rose-bg)',
          'rose-text': 'var(--color-tag-rose-text)',
        },

        // --- Asset Card Tag Colors ---
        'asset-tag': {
          '1-bg': 'var(--color-asset-tag-1-bg)',
          '1-text': 'var(--color-asset-tag-1-text)',
          '2-bg': 'var(--color-asset-tag-2-bg)',
          '2-text': 'var(--color-asset-tag-2-text)',
          '3-bg': 'var(--color-asset-tag-3-bg)',
          '3-text': 'var(--color-asset-tag-3-text)',
          '4-bg': 'var(--color-asset-tag-4-bg)',
          '4-text': 'var(--color-asset-tag-4-text)',
          '5-bg': 'var(--color-asset-tag-5-bg)',
          '5-text': 'var(--color-asset-tag-5-text)',
          'mechanism': 'var(--color-topbar-mechanism)',
          'indication': 'var(--color-subnav-indication)',
          'last-updated': 'var(--color-subnav-last-updated)',
        },
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        heading: 'var(--font-heading)',
        ui: 'var(--font-ui)',
      },
      fontSize: {
        '10': 'var(--text-10)',
        '9-5': 'var(--text-9-5)',
        '3xs': 'var(--text-3xs)',
        'placeholder-sm': 'var(--text-placeholder-sm)',
        '2xs': 'var(--text-2xs)',
        'icon-sm': 'var(--text-icon-sm)',
        xs: 'var(--text-xs)',
        'body-sm': 'var(--text-body-sm)',
        '13': 'var(--text-13)',
        sm: 'var(--text-sm)',
        'card-title': 'var(--text-card-title)',
        'detail-link': 'var(--text-detail-link)',
        base: 'var(--text-base)',
        'base-lg': 'var(--text-base-lg)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
      },
      fontWeight: {
        light: 'var(--font-light)',
        normal: 'var(--font-normal)',
        medium: 'var(--font-medium)',
        semibold: 'var(--font-semibold)',
        bold: 'var(--font-bold)',
      },
    },
  },
  plugins: [],
};
